// Copyright (c) 2026 Ant Group Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/runtime/v1/sandbox-api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_Start_FullMethodName                      = "/runtime.v1.SandboxService/Start"
	SandboxService_StartWithOperation_FullMethodName         = "/runtime.v1.SandboxService/StartWithOperation"
	SandboxService_GetStartOperation_FullMethodName          = "/runtime.v1.SandboxService/GetStartOperation"
	SandboxService_Checkpoint_FullMethodName                 = "/runtime.v1.SandboxService/Checkpoint"
	SandboxService_CheckpointIfGeneration_FullMethodName     = "/runtime.v1.SandboxService/CheckpointIfGeneration"
	SandboxService_CheckpointWithOperation_FullMethodName    = "/runtime.v1.SandboxService/CheckpointWithOperation"
	SandboxService_GetCheckpointOperation_FullMethodName     = "/runtime.v1.SandboxService/GetCheckpointOperation"
	SandboxService_RecoverCheckpointOperation_FullMethodName = "/runtime.v1.SandboxService/RecoverCheckpointOperation"
	SandboxService_Delete_FullMethodName                     = "/runtime.v1.SandboxService/Delete"
	SandboxService_DeleteIfGeneration_FullMethodName         = "/runtime.v1.SandboxService/DeleteIfGeneration"
	SandboxService_Wait_FullMethodName                       = "/runtime.v1.SandboxService/Wait"
	SandboxService_List_FullMethodName                       = "/runtime.v1.SandboxService/List"
	SandboxService_Stats_FullMethodName                      = "/runtime.v1.SandboxService/Stats"
	SandboxService_ListAvailableRuntimes_FullMethodName      = "/runtime.v1.SandboxService/ListAvailableRuntimes"
	SandboxService_SetNetworkPolicy_FullMethodName           = "/runtime.v1.SandboxService/SetNetworkPolicy"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService manages sandbox lifecycle and inspection operations.
type SandboxServiceClient interface {
	// Start creates and starts a sandbox.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// StartWithOperation starts a sandbox under an explicit, persistent
	// operation identity so a client that lost the reply can query or replay the
	// original operation instead of blindly re-creating the sandbox. The
	// operation record is node-local idempotency state; it is not a cross-node
	// writer lease or fencing token. Old servers that predate the RPC return
	// Unimplemented; callers must fail hard instead of falling back to Start.
	StartWithOperation(ctx context.Context, in *StartWithOperationRequest, opts ...grpc.CallOption) (*StartOperationStatus, error)
	// GetStartOperation returns the durable state of one start operation. It
	// never creates anything and never re-executes a past operation.
	GetStartOperation(ctx context.Context, in *GetStartOperationRequest, opts ...grpc.CallOption) (*StartOperationStatus, error)
	// Checkpoint saves a running sandbox into a caller-owned directory.
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// CheckpointIfGeneration checkpoints only the physical incarnation that
	// still carries the expected server-assigned resource generation. Old
	// servers that predate the RPC return Unimplemented; callers must not
	// fall back to the unconditional Checkpoint.
	CheckpointIfGeneration(ctx context.Context, in *CheckpointIfGenerationRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// CheckpointWithOperation checkpoints a running sandbox under an explicit,
	// persistent operation identity so a client that lost the reply can query
	// or replay the original checkpoint instead of re-running it against an
	// unproven source state. Only stop-and-copy Firecracker directory
	// checkpoints are supported; the operation record is node-local
	// idempotency state, not a cross-node writer lease or fencing token. Old
	// servers that predate the RPC return Unimplemented; callers must fail
	// hard instead of falling back to Checkpoint or CheckpointIfGeneration.
	// New admissions require a runtime with both the sealed-root writer and
	// the operation-witness capabilities and are recorded under recovery
	// protocol WITNESS; the exact operation binding is sent to the runtime and
	// a successful checkpoint acknowledges the retained evidence after the
	// SUCCEEDED fact is durable.
	CheckpointWithOperation(ctx context.Context, in *CheckpointWithOperationRequest, opts ...grpc.CallOption) (*CheckpointOperationStatus, error)
	// GetCheckpointOperation returns the durable state of one checkpoint
	// operation. It never starts a checkpoint and never re-executes a past
	// operation.
	GetCheckpointOperation(ctx context.Context, in *GetCheckpointOperationRequest, opts ...grpc.CallOption) (*CheckpointOperationStatus, error)
	// RecoverCheckpointOperation explicitly reconciles one already-recorded
	// checkpoint operation bound to the witness recovery protocol: it completes
	// the runtime's stop-source flow for an undetermined record and releases
	// the evidence-retention gate of a durable success. It never admits a new
	// operation, never takes a snapshot, never resumes the source, and never
	// falls back to Checkpoint, CheckpointIfGeneration, or
	// CheckpointWithOperation. A missing record is NotFound; a legacy
	// protocol-0 record, a FAILED record, and any binding mismatch are
	// refused.
	RecoverCheckpointOperation(ctx context.Context, in *RecoverCheckpointOperationRequest, opts ...grpc.CallOption) (*CheckpointOperationStatus, error)
	// Delete force-deletes a sandbox.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// DeleteIfGeneration retires one physical generation only when the sandbox
	// still carries the expected server-assigned resource generation.
	DeleteIfGeneration(ctx context.Context, in *DeleteIfGenerationRequest, opts ...grpc.CallOption) (*DeleteIfGenerationResponse, error)
	// Wait waits for a sandbox to exit.
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	// List lists sandboxes by filters.
	List(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	// Stats returns resource usage statistics for a sandbox.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// ListAvailableRuntimes lists runtime classes whose handlers are ready.
	ListAvailableRuntimes(ctx context.Context, in *ListAvailableRuntimesRequest, opts ...grpc.CallOption) (*ListAvailableRuntimesResponse, error)
	// SetNetworkPolicy atomically replaces the network policy of a running sandbox.
	SetNetworkPolicy(ctx context.Context, in *SetNetworkPolicyRequest, opts ...grpc.CallOption) (*SetNetworkPolicyResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, SandboxService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StartWithOperation(ctx context.Context, in *StartWithOperationRequest, opts ...grpc.CallOption) (*StartOperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOperationStatus)
	err := c.cc.Invoke(ctx, SandboxService_StartWithOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetStartOperation(ctx context.Context, in *GetStartOperationRequest, opts ...grpc.CallOption) (*StartOperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOperationStatus)
	err := c.cc.Invoke(ctx, SandboxService_GetStartOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, SandboxService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CheckpointIfGeneration(ctx context.Context, in *CheckpointIfGenerationRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, SandboxService_CheckpointIfGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CheckpointWithOperation(ctx context.Context, in *CheckpointWithOperationRequest, opts ...grpc.CallOption) (*CheckpointOperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointOperationStatus)
	err := c.cc.Invoke(ctx, SandboxService_CheckpointWithOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetCheckpointOperation(ctx context.Context, in *GetCheckpointOperationRequest, opts ...grpc.CallOption) (*CheckpointOperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointOperationStatus)
	err := c.cc.Invoke(ctx, SandboxService_GetCheckpointOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) RecoverCheckpointOperation(ctx context.Context, in *RecoverCheckpointOperationRequest, opts ...grpc.CallOption) (*CheckpointOperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointOperationStatus)
	err := c.cc.Invoke(ctx, SandboxService_RecoverCheckpointOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, SandboxService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteIfGeneration(ctx context.Context, in *DeleteIfGenerationRequest, opts ...grpc.CallOption) (*DeleteIfGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIfGenerationResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeleteIfGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, SandboxService_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) List(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, SandboxService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListAvailableRuntimes(ctx context.Context, in *ListAvailableRuntimesRequest, opts ...grpc.CallOption) (*ListAvailableRuntimesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableRuntimesResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListAvailableRuntimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SetNetworkPolicy(ctx context.Context, in *SetNetworkPolicyRequest, opts ...grpc.CallOption) (*SetNetworkPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNetworkPolicyResponse)
	err := c.cc.Invoke(ctx, SandboxService_SetNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService manages sandbox lifecycle and inspection operations.
type SandboxServiceServer interface {
	// Start creates and starts a sandbox.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// StartWithOperation starts a sandbox under an explicit, persistent
	// operation identity so a client that lost the reply can query or replay the
	// original operation instead of blindly re-creating the sandbox. The
	// operation record is node-local idempotency state; it is not a cross-node
	// writer lease or fencing token. Old servers that predate the RPC return
	// Unimplemented; callers must fail hard instead of falling back to Start.
	StartWithOperation(context.Context, *StartWithOperationRequest) (*StartOperationStatus, error)
	// GetStartOperation returns the durable state of one start operation. It
	// never creates anything and never re-executes a past operation.
	GetStartOperation(context.Context, *GetStartOperationRequest) (*StartOperationStatus, error)
	// Checkpoint saves a running sandbox into a caller-owned directory.
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// CheckpointIfGeneration checkpoints only the physical incarnation that
	// still carries the expected server-assigned resource generation. Old
	// servers that predate the RPC return Unimplemented; callers must not
	// fall back to the unconditional Checkpoint.
	CheckpointIfGeneration(context.Context, *CheckpointIfGenerationRequest) (*CheckpointResponse, error)
	// CheckpointWithOperation checkpoints a running sandbox under an explicit,
	// persistent operation identity so a client that lost the reply can query
	// or replay the original checkpoint instead of re-running it against an
	// unproven source state. Only stop-and-copy Firecracker directory
	// checkpoints are supported; the operation record is node-local
	// idempotency state, not a cross-node writer lease or fencing token. Old
	// servers that predate the RPC return Unimplemented; callers must fail
	// hard instead of falling back to Checkpoint or CheckpointIfGeneration.
	// New admissions require a runtime with both the sealed-root writer and
	// the operation-witness capabilities and are recorded under recovery
	// protocol WITNESS; the exact operation binding is sent to the runtime and
	// a successful checkpoint acknowledges the retained evidence after the
	// SUCCEEDED fact is durable.
	CheckpointWithOperation(context.Context, *CheckpointWithOperationRequest) (*CheckpointOperationStatus, error)
	// GetCheckpointOperation returns the durable state of one checkpoint
	// operation. It never starts a checkpoint and never re-executes a past
	// operation.
	GetCheckpointOperation(context.Context, *GetCheckpointOperationRequest) (*CheckpointOperationStatus, error)
	// RecoverCheckpointOperation explicitly reconciles one already-recorded
	// checkpoint operation bound to the witness recovery protocol: it completes
	// the runtime's stop-source flow for an undetermined record and releases
	// the evidence-retention gate of a durable success. It never admits a new
	// operation, never takes a snapshot, never resumes the source, and never
	// falls back to Checkpoint, CheckpointIfGeneration, or
	// CheckpointWithOperation. A missing record is NotFound; a legacy
	// protocol-0 record, a FAILED record, and any binding mismatch are
	// refused.
	RecoverCheckpointOperation(context.Context, *RecoverCheckpointOperationRequest) (*CheckpointOperationStatus, error)
	// Delete force-deletes a sandbox.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// DeleteIfGeneration retires one physical generation only when the sandbox
	// still carries the expected server-assigned resource generation.
	DeleteIfGeneration(context.Context, *DeleteIfGenerationRequest) (*DeleteIfGenerationResponse, error)
	// Wait waits for a sandbox to exit.
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	// List lists sandboxes by filters.
	List(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	// Stats returns resource usage statistics for a sandbox.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// ListAvailableRuntimes lists runtime classes whose handlers are ready.
	ListAvailableRuntimes(context.Context, *ListAvailableRuntimesRequest) (*ListAvailableRuntimesResponse, error)
	// SetNetworkPolicy atomically replaces the network policy of a running sandbox.
	SetNetworkPolicy(context.Context, *SetNetworkPolicyRequest) (*SetNetworkPolicyResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedSandboxServiceServer) StartWithOperation(context.Context, *StartWithOperationRequest) (*StartOperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWithOperation not implemented")
}
func (UnimplementedSandboxServiceServer) GetStartOperation(context.Context, *GetStartOperationRequest) (*StartOperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStartOperation not implemented")
}
func (UnimplementedSandboxServiceServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedSandboxServiceServer) CheckpointIfGeneration(context.Context, *CheckpointIfGenerationRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointIfGeneration not implemented")
}
func (UnimplementedSandboxServiceServer) CheckpointWithOperation(context.Context, *CheckpointWithOperationRequest) (*CheckpointOperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointWithOperation not implemented")
}
func (UnimplementedSandboxServiceServer) GetCheckpointOperation(context.Context, *GetCheckpointOperationRequest) (*CheckpointOperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpointOperation not implemented")
}
func (UnimplementedSandboxServiceServer) RecoverCheckpointOperation(context.Context, *RecoverCheckpointOperationRequest) (*CheckpointOperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverCheckpointOperation not implemented")
}
func (UnimplementedSandboxServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteIfGeneration(context.Context, *DeleteIfGenerationRequest) (*DeleteIfGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIfGeneration not implemented")
}
func (UnimplementedSandboxServiceServer) Wait(context.Context, *WaitRequest) (*WaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedSandboxServiceServer) List(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSandboxServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedSandboxServiceServer) ListAvailableRuntimes(context.Context, *ListAvailableRuntimesRequest) (*ListAvailableRuntimesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableRuntimes not implemented")
}
func (UnimplementedSandboxServiceServer) SetNetworkPolicy(context.Context, *SetNetworkPolicyRequest) (*SetNetworkPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNetworkPolicy not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StartWithOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWithOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).StartWithOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_StartWithOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).StartWithOperation(ctx, req.(*StartWithOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetStartOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStartOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetStartOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetStartOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetStartOperation(ctx, req.(*GetStartOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CheckpointIfGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointIfGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CheckpointIfGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CheckpointIfGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CheckpointIfGeneration(ctx, req.(*CheckpointIfGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CheckpointWithOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointWithOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CheckpointWithOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CheckpointWithOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CheckpointWithOperation(ctx, req.(*CheckpointWithOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetCheckpointOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetCheckpointOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetCheckpointOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetCheckpointOperation(ctx, req.(*GetCheckpointOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_RecoverCheckpointOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverCheckpointOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).RecoverCheckpointOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_RecoverCheckpointOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).RecoverCheckpointOperation(ctx, req.(*RecoverCheckpointOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteIfGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIfGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteIfGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteIfGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteIfGeneration(ctx, req.(*DeleteIfGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).List(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListAvailableRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableRuntimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListAvailableRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListAvailableRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListAvailableRuntimes(ctx, req.(*ListAvailableRuntimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SetNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SetNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SetNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SetNetworkPolicy(ctx, req.(*SetNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _SandboxService_Start_Handler,
		},
		{
			MethodName: "StartWithOperation",
			Handler:    _SandboxService_StartWithOperation_Handler,
		},
		{
			MethodName: "GetStartOperation",
			Handler:    _SandboxService_GetStartOperation_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _SandboxService_Checkpoint_Handler,
		},
		{
			MethodName: "CheckpointIfGeneration",
			Handler:    _SandboxService_CheckpointIfGeneration_Handler,
		},
		{
			MethodName: "CheckpointWithOperation",
			Handler:    _SandboxService_CheckpointWithOperation_Handler,
		},
		{
			MethodName: "GetCheckpointOperation",
			Handler:    _SandboxService_GetCheckpointOperation_Handler,
		},
		{
			MethodName: "RecoverCheckpointOperation",
			Handler:    _SandboxService_RecoverCheckpointOperation_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SandboxService_Delete_Handler,
		},
		{
			MethodName: "DeleteIfGeneration",
			Handler:    _SandboxService_DeleteIfGeneration_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _SandboxService_Wait_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SandboxService_List_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _SandboxService_Stats_Handler,
		},
		{
			MethodName: "ListAvailableRuntimes",
			Handler:    _SandboxService_ListAvailableRuntimes_Handler,
		},
		{
			MethodName: "SetNetworkPolicy",
			Handler:    _SandboxService_SetNetworkPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/runtime/v1/sandbox-api.proto",
}
